import { Injectable, NotFoundException } from '@nestjs/common';
import { CreatePlantDto, PlantDto, UpdatePlantDto } from './dto/plant.dto';
import { CreateDiseaseDto, DiseaseDto } from './dto/disease.dto';

@Injectable()
export class PlantsService {
  private plants: PlantDto[] = [
    {
      id: '1',
      name: 'Monstera Deliciosa',
      scientificName: 'Monstera deliciosa',
      description: 'Planta tropical con hojas grandes y perforadas. Popular como planta de interior por su follaje exótico y su fácil cuidado.',
      imageUrl: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b',
      category: 'Interior',
      careLevel: 'easy',
      wateringFrequency: 'Cada 7-10 días',
      sunlightRequirement: 'Luz indirecta brillante',
      temperature: '18-27°C',
      commonDiseases: ['root-rot', 'spider-mites', 'leaf-spot', 'scale-insects'],
    },
    {
      id: '2',
      name: 'Pothos',
      scientificName: 'Epipremnum aureum',
      description: 'Planta trepadora muy resistente, ideal para principiantes. Purifica el aire y crece rápidamente.',
      imageUrl: 'https://images.unsplash.com/photo-1593482892540-73c6e536b1d1',
      category: 'Interior',
      careLevel: 'easy',
      wateringFrequency: 'Cada 7 días',
      sunlightRequirement: 'Luz baja a media',
      temperature: '15-29°C',
      commonDiseases: ['root-rot', 'fungus-gnats', 'spider-mites'],
    },
    {
      id: '3',
      name: 'Ficus Lyrata',
      scientificName: 'Ficus lyrata',
      description: 'Árbol de interior con hojas grandes en forma de violín. Requiere cuidados más específicos pero es muy decorativo.',
      imageUrl: 'https://images.unsplash.com/photo-1610394640921-f2e5628eebee',
      category: 'Interior',
      careLevel: 'medium',
      wateringFrequency: 'Cada 7-10 días',
      sunlightRequirement: 'Luz brillante indirecta',
      temperature: '18-24°C',
      commonDiseases: ['root-rot', 'leaf-spot', 'scale-insects', 'spider-mites'],
    },
    {
      id: '4',
      name: 'Tomate',
      scientificName: 'Solanum lycopersicum',
      description: 'Planta de cultivo que produce frutos comestibles. Requiere sol pleno y riego constante para buena producción.',
      imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa',
      category: 'Huerto',
      careLevel: 'medium',
      wateringFrequency: 'Diariamente',
      sunlightRequirement: 'Sol pleno (6-8 horas)',
      temperature: '20-30°C',
      commonDiseases: ['blight', 'powdery-mildew', 'mosaic-virus', 'bacterial-wilt', 'aphids'],
    },
    {
      id: '5',
      name: 'Suculenta Echeveria',
      scientificName: 'Echeveria elegans',
      description: 'Suculenta en forma de roseta con hojas carnosas azul-verdosas. Perfecta para jardines de rocas y macetas.',
      imageUrl: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc',
      category: 'Suculentas',
      careLevel: 'easy',
      wateringFrequency: 'Cada 14-21 días',
      sunlightRequirement: 'Sol directo parcial',
      temperature: '15-30°C',
      commonDiseases: ['root-rot', 'mealybugs', 'aphids'],
    },
    {
      id: '6',
      name: 'Sansevieria',
      scientificName: 'Sansevieria trifasciata',
      description: 'También conocida como "Lengua de Suegra". Extremadamente resistente y purificadora del aire. Ideal para principiantes.',
      imageUrl: 'https://images.unsplash.com/photo-1593482892891-63085a276e59',
      category: 'Interior',
      careLevel: 'easy',
      wateringFrequency: 'Cada 14-21 días',
      sunlightRequirement: 'Luz baja a alta',
      temperature: '15-29°C',
      commonDiseases: ['root-rot', 'spider-mites'],
    },
    {
      id: '7',
      name: 'Albahaca',
      scientificName: 'Ocimum basilicum',
      description: 'Hierba aromática esencial en la cocina mediterránea. Crece rápido y necesita cosecha regular.',
      imageUrl: 'https://images.unsplash.com/photo-1618375569909-3c8616cf7733',
      category: 'Huerto',
      careLevel: 'easy',
      wateringFrequency: 'Cada 2-3 días',
      sunlightRequirement: 'Sol pleno (6+ horas)',
      temperature: '18-26°C',
      commonDiseases: ['powdery-mildew', 'aphids', 'fungus-gnats', 'downy-mildew'],
    },
    {
      id: '8',
      name: 'Aloe Vera',
      scientificName: 'Aloe barbadensis miller',
      description: 'Suculenta medicinal con propiedades curativas. Fácil de cuidar y propaga fácilmente.',
      imageUrl: 'https://images.unsplash.com/photo-1596548438137-d51ea5c83ca5',
      category: 'Suculentas',
      careLevel: 'easy',
      wateringFrequency: 'Cada 21 días',
      sunlightRequirement: 'Sol indirecto brillante',
      temperature: '13-27°C',
      commonDiseases: ['root-rot', 'scale-insects', 'aloe-rust'],
    },
    {
      id: '9',
      name: 'Rosa',
      scientificName: 'Rosa spp.',
      description: 'Flor clásica de jardín con fragrancia embriagadora. Requiere cuidados regulares pero muy gratificante.',
      imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23',
      category: 'Exterior',
      careLevel: 'hard',
      wateringFrequency: 'Cada 3-4 días',
      sunlightRequirement: 'Sol pleno (6-8 horas)',
      temperature: '15-28°C',
      commonDiseases: ['black-spot', 'powdery-mildew', 'aphids', 'rose-rust', 'botrytis'],
    },
    {
      id: '10',
      name: 'Orquídea Phalaenopsis',
      scientificName: 'Phalaenopsis spp.',
      description: 'Orquídea mariposa, una de las más fáciles de cultivar en interior. Florece durante meses.',
      imageUrl: 'https://images.unsplash.com/photo-1615715616181-6b4c65b9b3ee',
      category: 'Interior',
      careLevel: 'medium',
      wateringFrequency: 'Cada 7-10 días (por inmersión)',
      sunlightRequirement: 'Luz indirecta brillante',
      temperature: '18-25°C',
      commonDiseases: ['root-rot', 'crown-rot', 'scale-insects', 'mealybugs'],
    },
    {
      id: '11',
      name: 'Pimiento',
      scientificName: 'Capsicum annuum',
      description: 'Planta de huerto productiva que da frutos coloridos. Excelente para principiantes en el cultivo de vegetales.',
      imageUrl: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83',
      category: 'Huerto',
      careLevel: 'medium',
      wateringFrequency: 'Cada 2-3 días',
      sunlightRequirement: 'Sol pleno (6-8 horas)',
      temperature: '21-29°C',
      commonDiseases: ['blight', 'aphids', 'bacterial-wilt', 'mosaic-virus'],
    },
    {
      id: '12',
      name: 'Helecho de Boston',
      scientificName: 'Nephrolepis exaltata',
      description: 'Helecho frondoso que aporta elegancia a cualquier espacio. Excelente humidificador natural.',
      imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae',
      category: 'Interior',
      careLevel: 'medium',
      wateringFrequency: 'Cada 3-5 días',
      sunlightRequirement: 'Luz indirecta media',
      temperature: '16-24°C',
      commonDiseases: ['root-rot', 'scale-insects', 'fungus-gnats', 'leaf-spot'],
    },
    {
      id: '13',
      name: 'Lavanda',
      scientificName: 'Lavandula angustifolia',
      description: 'Planta aromática perenne con flores violetas fragantes. Atrae polinizadores y repele plagas.',
      imageUrl: 'https://images.unsplash.com/photo-1595899346411-59518e6f2bc8',
      category: 'Exterior',
      careLevel: 'easy',
      wateringFrequency: 'Cada 5-7 días',
      sunlightRequirement: 'Sol pleno (8+ horas)',
      temperature: '15-30°C',
      commonDiseases: ['root-rot', 'leaf-spot', 'botrytis'],
    },
    {
      id: '14',
      name: 'Cactus San Pedro',
      scientificName: 'Echinopsis pachanoi',
      description: 'Cactus columnar de crecimiento rápido. Muy resistente a la sequía y fácil de cuidar.',
      imageUrl: 'https://images.unsplash.com/photo-1509937528035-ad76254b0356',
      category: 'Suculentas',
      careLevel: 'easy',
      wateringFrequency: 'Cada 21-30 días',
      sunlightRequirement: 'Sol pleno',
      temperature: '10-30°C',
      commonDiseases: ['root-rot', 'scale-insects', 'mealybugs'],
    },
    {
      id: '15',
      name: 'Geranio',
      scientificName: 'Pelargonium spp.',
      description: 'Planta floral muy popular con variedad de colores. Perfecta para balcones y jardines.',
      imageUrl: 'https://images.unsplash.com/photo-1592150621744-aca64f48394a',
      category: 'Exterior',
      careLevel: 'easy',
      wateringFrequency: 'Cada 3-4 días',
      sunlightRequirement: 'Sol pleno a parcial',
      temperature: '15-27°C',
      commonDiseases: ['botrytis', 'rust', 'whiteflies', 'aphids'],
    },
    {
      id: '16',
      name: 'Cilantro',
      scientificName: 'Coriandrum sativum',
      description: 'Hierba aromática esencial en muchas cocinas. Crece rápido y se cosecha fácilmente.',
      imageUrl: 'https://images.unsplash.com/photo-1617478091428-8770cafb52c6',
      category: 'Huerto',
      careLevel: 'easy',
      wateringFrequency: 'Cada 2-3 días',
      sunlightRequirement: 'Sol parcial (4-6 horas)',
      temperature: '17-27°C',
      commonDiseases: ['leaf-spot', 'powdery-mildew', 'aphids'],
    },
    {
      id: '17',
      name: 'Calathea',
      scientificName: 'Calathea spp.',
      description: 'Planta de interior con patrones únicos en las hojas. Sus hojas se mueven siguiendo la luz.',
      imageUrl: 'https://images.unsplash.com/photo-1614594895304-fe7116ac3b58',
      category: 'Interior',
      careLevel: 'hard',
      wateringFrequency: 'Cada 4-7 días',
      sunlightRequirement: 'Luz indirecta media a baja',
      temperature: '18-24°C',
      commonDiseases: ['spider-mites', 'leaf-spot', 'root-rot', 'fungus-gnats'],
    },
    {
      id: '18',
      name: 'Fresa',
      scientificName: 'Fragaria × ananassa',
      description: 'Planta perenne que produce frutos dulces y jugosos. Ideal para macetas y jardines pequeños.',
      imageUrl: 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2',
      category: 'Huerto',
      careLevel: 'medium',
      wateringFrequency: 'Cada 2-3 días',
      sunlightRequirement: 'Sol pleno (6-8 horas)',
      temperature: '15-26°C',
      commonDiseases: ['powdery-mildew', 'botrytis', 'spider-mites', 'verticillium-wilt'],
    },
  ];

  private diseases: DiseaseDto[] = [
    {
      id: 'root-rot',
      name: 'Pudrición de Raíz',
      type: 'fungal',
      description: 'La pudrición de raíz es una enfermedad fúngica común causada por exceso de agua y mal drenaje. Los hongos patógenos como Pythium, Phytophthora y Rhizoctonia atacan las raíces cuando están constantemente húmedas, impidiendo que la planta absorba nutrientes y agua.',
      symptoms: [
        'Hojas amarillas que comienzan desde la parte inferior',
        'Hojas caídas y marchitas a pesar del riego',
        'Raíces marrones, negras y blandas al tacto',
        'Olor desagradable a podrido del sustrato',
        'Crecimiento lento o detenido',
        'Base del tallo oscurecida',
      ],
      treatment: 'Saca la planta de la maceta inmediatamente. Corta todas las raíces podridas con tijeras esterilizadas. Lava las raíces sanas con agua limpia. Replanta en sustrato fresco y bien drenante. Reduce significativamente la frecuencia de riego y asegura buen drenaje. Considera usar fungicida sistémico si la infección es severa.',
      prevention: 'Usa siempre macetas con agujeros de drenaje adecuados. Elige sustratos bien drenantes mezclando perlita o arena. Riega solo cuando la capa superior del sustrato esté seca. Evita dejar agua en los platillos. Asegura buena circulación de aire alrededor de las raíces.',
      imageUrl: 'https://images.unsplash.com/photo-1583051331670-2fdf4ab50c1f',
    },
    {
      id: 'spider-mites',
      name: 'Ácaros Araña',
      type: 'pest',
      description: 'Los ácaros araña son plagas microscópicas (Tetranychus urticae) que se alimentan de la savia de las plantas perforando las células. Son especialmente problemáticos en ambientes secos y cálidos, pudiendo reproducirse rápidamente y formar grandes colonias.',
      symptoms: [
        'Pequeños puntos blancos o amarillos en las hojas (picaduras)',
        'Telarañas finas y sedosas entre hojas y tallos',
        'Hojas que se tornan amarillas, bronceadas o plateadas',
        'Crecimiento lento y debilitamiento general',
        'Caída prematura de hojas',
        'Ácaros visibles como puntos móviles (con lupa)',
      ],
      treatment: 'Aísla la planta infectada inmediatamente. Lava las hojas con agua jabonosa tibia, prestando especial atención al envés. Aplica aceite de neem cada 5-7 días durante 3 semanas. Para infestaciones severas, usa acaricida específico. Aumenta la humedad ambiental con nebulizaciones regulares.',
      prevention: 'Mantén humedad ambiental alta (50-60%) mediante nebulizaciones. Inspecciona regularmente el envés de las hojas. Limpia las hojas con paño húmedo semanalmente. Mantén las plantas saludables con nutrición adecuada. Introduce ácaros depredadores beneficiosos en jardines.',
      imageUrl: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8',
    },
    {
      id: 'leaf-spot',
      name: 'Manchas Foliares',
      type: 'fungal',
      description: 'Las manchas foliares son causadas por diversos hongos patógenos (Cercospora, Septoria, Alternaria) que infectan el tejido foliar. Estas enfermedades prosperan en condiciones húmedas y pueden propagarse rápidamente por salpicaduras de agua y esporas transportadas por el viento.',
      symptoms: [
        'Manchas circulares marrones, negras o rojizas en hojas',
        'Halos amarillos alrededor de las manchas',
        'Las manchas pueden fusionarse formando áreas necróticas grandes',
        'Hojas que amarillean y caen prematuramente',
        'Defoliación severa en casos avanzados',
        'Posibles anillos concéntricos en las manchas (ojo de buey)',
      ],
      treatment: 'Remueve y destruye todas las hojas afectadas inmediatamente. No las compostes. Mejora la circulación de aire podando si es necesario. Aplica fungicida a base de cobre o azufre según instrucciones. Evita mojar el follaje al regar. Reduce la humedad ambiental si es posible.',
      prevention: 'Riega siempre al nivel del suelo, nunca sobre las hojas. Asegura excelente circulación de aire entre plantas. Evita el hacinamiento de plantas. Limpia herramientas de poda con alcohol. Elimina hojas caídas del suelo regularmente. Aplica mantillo para evitar salpicaduras desde el suelo.',
      imageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399',
    },
    {
      id: 'powdery-mildew',
      name: 'Oídio o Mildiu Polvoriento',
      type: 'fungal',
      description: 'El oídio es causado por diversos hongos parásitos obligados (principalmente Erysiphe, Sphaerotheca, Podosphaera) que crecen en la superficie de hojas, tallos y frutos. A diferencia de otros hongos, prospera tanto en condiciones secas como húmedas, siendo más común en primavera y otoño.',
      symptoms: [
        'Polvo blanco o grisáceo en superficie de hojas y tallos',
        'Manchas pulverulentas que se expanden rápidamente',
        'Hojas que se curvan, deforman o retuercen',
        'Crecimiento atrofiado y reducido',
        'Hojas que amarillean y caen prematuramente',
        'Frutos y flores deformados',
        'Brotes nuevos cubiertos de polvo blanco',
      ],
      treatment: 'Mezcla 1 cucharada de bicarbonato de sodio con 1 litro de agua y unas gotas de jabón líquido, rocía semanalmente. Aplica fungicida específico para oídio en casos severos. Poda partes muy afectadas. Aplica azufre en polvo (no en temperaturas sobre 32°C). Mejora ventilación y reduce humedad nocturna.',
      prevention: 'Planta variedades resistentes cuando sea posible. Espaciado adecuado entre plantas para buena circulación. Poda para abrir el centro de la planta. Evita fertilización excesiva con nitrógeno. Riega temprano en el día para que las plantas sequen antes de la noche. Elimina material vegetal infectado.',
      imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b',
    },
    {
      id: 'blight',
      name: 'Tizón Tardío',
      type: 'fungal',
      description: 'El tizón tardío es causado por Phytophthora infestans, el mismo patógeno responsable de la Gran Hambruna Irlandesa. Es una enfermedad devastadora que afecta principalmente a tomates y papas, pudiendo destruir plantas completas en pocos días bajo condiciones óptimas de humedad y temperatura.',
      symptoms: [
        'Manchas marrones o negras irregulares en hojas',
        'Lesiones acuosas en tallos que se vuelven marrones',
        'Manchas marrones hundidas en frutos',
        'Moho blanco en el envés de hojas en condiciones húmedas',
        'Muerte rápida de hojas y tallos',
        'Olor desagradable de tejido en descomposición',
        'Colapso total de la planta en casos severos',
      ],
      treatment: 'Actúa inmediatamente al primer signo. Remueve y destruye todas las partes afectadas (no compostes). Aplica fungicida a base de cobre cada 5-7 días. En casos severos, considera remover toda la planta para proteger otras. Aplica fungicidas preventivos si hay pronóstico de condiciones favorables. Mejora drenaje y circulación de aire.',
      prevention: 'Usa variedades resistentes certificadas. Practica rotación de cultivos estricta (no tomates/papas en mismo lugar por 3 años). Espaciado amplio entre plantas. Instala tutores para mantener plantas fuera del suelo. Riega solo en la base de plantas. Aplica mantillo. Monitorea previsiones de tizón y aplica fungicidas preventivos. Elimina plantas voluntarias y malezas solanáceas.',
      imageUrl: 'https://images.unsplash.com/photo-1592419044706-39796d40f98c',
    },
    {
      id: 'mosaic-virus',
      name: 'Virus del Mosaico',
      type: 'viral',
      description: 'Los virus del mosaico (TMV, CMV) son patógenos altamente contagiosos que se transmiten mecánicamente a través de herramientas, manos, semillas y especialmente por insectos vectores como pulgones y trips. Una vez que una planta está infectada, no hay cura y el virus permanece activo en restos de plantas.',
      symptoms: [
        'Patrón de mosaico en hojas con áreas verde claro y oscuro',
        'Hojas deformadas, arrugadas o con forma de cuchara',
        'Ampollas o burbujas en la superficie de las hojas',
        'Crecimiento atrofiado y enanismo',
        'Frutos pequeños, deformes y con manchas',
        'Reducción severa en la producción',
        'Venas transparentes o aclaradas',
        'Necrosis en casos severos',
      ],
      treatment: 'NO HAY CURA para virus. La única opción es remover y destruir plantas infectadas inmediatamente (quémalas o tíralas a la basura, nunca compostes). Desinfecta todas las herramientas con lejía al 10%. Lávate las manos después de tocar plantas infectadas. Control riguroso de insectos vectores con aceite de neem o insecticidas.',
      prevention: 'Usa solo semillas certificadas libres de virus. Planta variedades resistentes. Control estricto de pulgones, trips y otros insectos vectores. Lava manos y desinfecta herramientas frecuentemente. Elimina malezas que pueden hospedar virus. No fumes cerca de plantas (el tabaco puede transmitir TMV). Inspecciona plantas nuevas cuidadosamente antes de introducirlas. Mantén plantas saludables para aumentar resistencia.',
      imageUrl: 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e',
    },
    {
      id: 'aphids',
      name: 'Pulgones o Áfidos',
      type: 'pest',
      description: 'Los pulgones son insectos pequeños de cuerpo blando que se alimentan de la savia de las plantas. Forman colonias densas en brotes tiernos, hojas jóvenes y tallos. Se reproducen asexualmente muy rápidamente, y una sola hembra puede generar miles de descendientes en pocas semanas. Además, secretan melaza que atrae hormigas y promueve fumagina.',
      symptoms: [
        'Insectos pequeños verdes, negros, amarillos o rosados en racimos',
        'Hojas enrolladas, distorsionadas o arrugadas',
        'Brotes nuevos deformados y débiles',
        'Sustancia pegajosa brillante en hojas (melaza)',
        'Moho negro en hojas (fumagina sobre melaza)',
        'Hormigas subiendo y bajando por la planta',
        'Crecimiento lento y debilitado',
        'Posible transmisión de virus',
      ],
      treatment: 'Rocía agua a presión para desalojar pulgones. Aplica jabón insecticida o mezcla de agua con jabón suave (no detergente). Usa aceite de neem cada 7 días. Para infestaciones severas, usa insecticida piretrina. Introduce mariquitas, crisopas o avispas parasitoides. Elimina hormigas que protegen pulgones.',
      prevention: 'Inspecciona plantas semanalmente, especialmente brotes nuevos. Planta flores que atraen insectos beneficiosos (caléndula, eneldo, milenrama). Usa mantillo reflectante plateado. Evita exceso de fertilización nitrogenada que produce crecimiento tierno. Planta cultivos trampa como capuchinas. Mantén plantas saludables. Introduce insectos beneficiosos preventivamente.',
      imageUrl: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a',
    },
    {
      id: 'fungus-gnats',
      name: 'Mosquitos del Sustrato',
      type: 'pest',
      description: 'Los mosquitos del sustrato son pequeñas moscas negras cuyos adultos son principalmente molestos, pero sus larvas blancas que viven en el sustrato pueden dañar raíces, especialmente de plántulas. Prosperan en sustratos constantemente húmedos y ricos en materia orgánica en descomposición.',
      symptoms: [
        'Pequeñas moscas negras volando alrededor de plantas',
        'Mosquitos emergiendo del sustrato al regar',
        'Larvas blancas translúcidas en el sustrato (5-6mm)',
        'Plántulas que se marchitan o mueren',
        'Crecimiento lento sin razón aparente',
        'Raíces dañadas por alimentación de larvas',
      ],
      treatment: 'Deja secar el sustrato entre riegos (las larvas mueren en sustrato seco). Coloca trampas amarillas adhesivas para adultos. Aplica tierra de diatomeas sobre el sustrato. Usa Bacillus thuringiensis israelensis (BTI) en el agua de riego. Cubrir sustrato con arena fina (2cm). Nematodos beneficiosos para controlar larvas.',
      prevention: 'No sobre-riegues; deja secar 2-3cm superiores del sustrato. Usa sustrato de calidad bien drenante. Evita sustratos con exceso de turba. Retira hojas caídas y materia orgánica en descomposición. Mejora circulación de aire. No dejes agua estancada. Usa macetas con buen drenaje.',
      imageUrl: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a',
    },
    {
      id: 'scale-insects',
      name: 'Cochinillas o Insectos Escama',
      type: 'pest',
      description: 'Las cochinillas son insectos de cuerpo blando cubiertos por una escama cerosa protectora. Se adhieren a tallos y hojas, permaneciendo inmóviles mientras se alimentan de savia. Hay dos tipos principales: cochinillas blandas que producen melaza y cochinillas blindadas más difíciles de controlar.',
      symptoms: [
        'Protuberancias marrones, blancas o amarillas en tallos y hojas',
        'Sustancia pegajosa en hojas (melaza)',
        'Moho negro (fumagina) sobre la melaza',
        'Hojas amarillentas y que caen',
        'Crecimiento debilitado y lento',
        'Muerte de ramas en infestaciones severas',
        'Hormigas atraídas por la melaza',
      ],
      treatment: 'Raspa cochinillas manualmente con uña o cepillo suave. Limpia con algodón empapado en alcohol isopropílico. Aplica aceite hortícola o de neem que sofoca las cochinillas. Repite tratamiento cada 7-10 días durante varias semanas. Para infestaciones severas, poda partes muy afectadas. Introduce mariquitas y avispas parasitoides.',
      prevention: 'Inspecciona cuidadosamente plantas nuevas antes de comprar. Mantén plantas saludables con nutrición adecuada. Limpia hojas regularmente. Mejora circulación de aire. Evita exceso de nitrógeno. Inspecciona regularmente especialmente en uniones de tallos. Aísla plantas infectadas inmediatamente.',
      imageUrl: 'https://images.unsplash.com/photo-1530836176872-14c89f41db1a?w=800',
    },
    {
      id: 'mealybugs',
      name: 'Cochinillas Algodonosas',
      type: 'pest',
      description: 'Las cochinillas harinosas son insectos de cuerpo blando cubiertos de una sustancia cerosa blanca algodonosa. Se esconden en grietas, pliegues de hojas y uniones de tallos. Se mueven lentamente y forman colonias. Son especialmente problemáticas en plantas de interior y suculentas.',
      symptoms: [
        'Grupos de sustancia blanca algodonosa en plantas',
        'Masas blancas en uniones de hojas y tallos',
        'Melaza pegajosa en hojas',
        'Hojas amarillentas y distorsionadas',
        'Crecimiento lento y debilitado',
        'Caída prematura de hojas',
        'Moho negro (fumagina)',
      ],
      treatment: 'Aísla la planta inmediatamente. Limpia con hisopos de algodón empapados en alcohol al 70%. Rocía con agua jabonosa o aceite de neem cada 5-7 días. Para infestaciones en raíces, saca la planta, lava raíces y replanta en sustrato fresco. En casos severos, usa insecticida sistémico. Introduce mariquitas criptolaemus.',
      prevention: 'Inspecciona plantas nuevas minuciosamente, incluyendo raíces. Revisa regularmente pliegues y uniones de hojas. Mantén buena circulación de aire. Evita sobre-fertilización. Limpia hojas regularmente. Aísla plantas infectadas inmediatamente. No sobre-riegues (favorece cochinillas de raíz).',
      imageUrl: 'https://images.unsplash.com/photo-1614594895304-fe7116ac3b58?w=800',
    },
    {
      id: 'bacterial-wilt',
      name: 'Marchitez Bacteriana',
      type: 'bacterial',
      description: 'La marchitez bacteriana es causada por Ralstonia solanacearum, una bacteria que vive en el suelo e infecta plantas a través de heridas en raíces. Coloniza el sistema vascular, bloqueando el transporte de agua. Es especialmente devastadora en solanáceas (tomate, pimiento, berenjena) en climas cálidos y húmedos.',
      symptoms: [
        'Marchitez repentina durante el día que se recupera de noche (inicialmente)',
        'Marchitez permanente a medida que progresa',
        'Hojas que permanecen verdes aunque marchitas',
        'Decoloración marrón del sistema vascular (cortar tallo)',
        'Exudación bacteriana lechosa blanca al cortar tallo',
        'Muerte rápida de toda la planta',
        'Sin amarillamiento típico de otras enfermedades',
      ],
      treatment: 'NO HAY CURA efectiva una vez infectada. Remueve y destruye plantas infectadas inmediatamente (quémalas, no compostes). Desinfecta herramientas con lejía al 10%. No plantes solanáceas en ese suelo por al menos 3 años. Considera solarización del suelo. Mejora drenaje del suelo.',
      prevention: 'Planta variedades resistentes cuando estén disponibles. Practica rotación de cultivos rigurosa (5+ años sin solanáceas). Usa plantines certificados libres de enfermedad. Evita heridas en raíces. Mejora drenaje del suelo. Evita mover suelo de áreas infectadas. Controla nematodos que crean heridas. Desinfecta herramientas entre plantas. Solariza suelo antes de plantar.',
      imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=800',
    },
    {
      id: 'botrytis',
      name: 'Moho Gris o Botrytis',
      type: 'fungal',
      description: 'Botrytis cinerea es un hongo necrotrófico que ataca tejidos debilitados, dañados o senescentes. Produce un moho gris característico y miles de esporas que se dispersan fácilmente. Prospera en condiciones de humedad alta, temperaturas frescas y poca ventilación. Afecta flores, frutos, hojas y tallos.',
      symptoms: [
        'Moho gris aterciopelado en flores, hojas o frutos',
        'Manchas marrones acuosas que se expanden rápidamente',
        'Pétalos que se vuelven papiráceos y marrones',
        'Frutos que se pudren con moho gris',
        'Tallos con lesiones café que los debilitan',
        'Caída de flores y frutos prematuramente',
        'Anillos concéntricos en manchas de frutos',
      ],
      treatment: 'Remueve inmediatamente todo el tejido infectado (corta 5cm más allá de la infección). Mejora drasticamente la circulación de aire. Reduce humedad ambiental. Evita mojar follaje. Aplica fungicida a base de cobre o específico para botrytis. Abre invernaderos para ventilar. Reduce riego.',
      prevention: 'Asegura excelente circulación de aire mediante espaciado adecuado. Evita mojar follaje al regar, riega temprano. Remueve flores marchitas y hojas muertas inmediatamente. No sobre-fertilices con nitrógeno. Poda para abrir centro de plantas. Usa ventiladores en invernaderos. Calienta invernaderos antes del amanecer. Mantén humedad debajo de 85%.',
      imageUrl: 'https://images.unsplash.com/photo-1578059760971-c0296c6b4ba9?w=800',
    },
    {
      id: 'black-spot',
      name: 'Mancha Negra de las Rosas',
      type: 'fungal',
      description: 'La mancha negra (Diplocarpon rosae) es la enfermedad fúngica más común en rosas. Las esporas invernan en hojas caídas y cañas infectadas, germinando en primavera con agua libre en las hojas. Puede causar defoliación severa, debilitando plantas y reduciendo floración.',
      symptoms: [
        'Manchas circulares negras con bordes irregulares en hojas',
        'Halos amarillos alrededor de las manchas negras',
        'Las manchas se expanden y fusionan',
        'Amarillamiento de hojas afectadas',
        'Defoliación severa empezando desde abajo',
        'Cañas débiles con menos flores',
        'Nueva infección cada primavera',
      ],
      treatment: 'Remueve todas las hojas afectadas inmediatamente. Rastrilla y destruye hojas caídas. Aplica fungicida a base de cobre, azufre o productos específicos para rosas cada 7-14 días. Alterna fungicidas para evitar resistencia. Continúa tratamiento preventivo toda la temporada. Poda cañas infectadas.',
      prevention: 'Planta variedades resistentes certificadas. Espaciado amplio para circulación de aire. Riega solo en la base temprano en el día. Aplica mantillo para evitar salpicaduras desde el suelo. Remueve y destruye todas las hojas caídas en otoño. Poda sanitaria en invierno. Aplica fungicidas preventivos en primavera. Limpia herramientas entre plantas.',
      imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
    },
    {
      id: 'crown-rot',
      name: 'Pudrición de Corona',
      type: 'fungal',
      description: 'La pudrición de corona afecta la base de la planta donde el tallo se encuentra con las raíces. Causada por diversos hongos del suelo (Phytophthora, Pythium, Rhizoctonia) y favorecida por plantación profunda, suelos pesados y exceso de humedad. Es especialmente mortal porque afecta el punto de crecimiento.',
      symptoms: [
        'Oscurecimiento de la base del tallo',
        'Tejido blando y acuoso en la corona',
        'Marchitez repentina de toda la planta',
        'Hojas amarillentas aunque el sustrato esté húmedo',
        'Caída prematura de hojas',
        'Moho blanco o gris en la base del tallo',
        'Muerte rápida de la planta',
      ],
      treatment: 'Si se detecta temprano, remueve sustrato alrededor de la corona. Corta tejido podrido hasta tejido sano. Aplica fungicida a la corona. Deja secar bien antes de regar nuevamente. Replanta más superficialmente en sustrato fresco y bien drenante. En casos avanzados, descarta la planta.',
      prevention: 'Planta a la profundidad correcta (no entierres la corona). Usa sustrato muy bien drenante. Macetas con excelente drenaje. No sobre-riegues. Permite que el sustrato seque entre riegos. Evita agua estancada alrededor de la corona. No acumules mantillo contra tallos. Mejora drenaje en jardín con enmiendas.',
      imageUrl: 'https://images.unsplash.com/photo-1615715616181-6b4c65b9b3ee?w=800',
    },
    {
      id: 'rust',
      name: 'Roya',
      type: 'fungal',
      description: 'Las royas son causadas por hongos especializados del orden Pucciniales. Producen pústulas de esporas de color naranja, amarillo, marrón o rojo que parecen polvo oxidado. Muchas royas requieren dos hospederos para completar su ciclo de vida. Las esporas se dispersan por viento y lluvia.',
      symptoms: [
        'Pústulas en polvo naranja, amarillo o marrón en envés de hojas',
        'Manchas amarillas o cloróticas en haz de hojas',
        'Las pústulas liberan polvo (esporas) al tocarlas',
        'Hojas que amarillean y caen prematuramente',
        'Defoliación severa en infecciones fuertes',
        'Puede afectar tallos y frutos en algunos casos',
        'Crecimiento debilitado',
      ],
      treatment: 'Remueve y destruye hojas afectadas (no compostes). Mejora circulación de aire. Aplica fungicida a base de azufre o productos específicos para roya. Trata cada 7-14 días. Evita mojar follaje. En jardines, considera remover hospederos alternativos si se conocen.',
      prevention: 'Planta variedades resistentes. Espaciado amplio entre plantas. Riega temprano en el día solo en la base. Mejora circulación con poda selectiva. Remueve hojas caídas. Evita fertilización excesiva con nitrógeno. Rota ubicaciones de plantas anuales. Algunos royas requieren remover hospedero alternativo (ej: enebros para roya del manzano).',
      imageUrl: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=800',
    },
    {
      id: 'whiteflies',
      name: 'Moscas Blancas',
      type: 'pest',
      description: 'Las moscas blancas son pequeños insectos blancos con alas cerosas que se parecen a pequeñas polillas. Se alimentan de savia en el envés de las hojas. Vuelan en nubes cuando se disturban. Se reproducen rápidamente, especialmente en invernaderos y climas cálidos. Transmiten virus y producen melaza.',
      symptoms: [
        'Nubes de pequeños insectos blancos al mover la planta',
        'Insectos blancos triangulares en envés de hojas',
        'Hojas que amarillean y se caen',
        'Melaza pegajosa en hojas',
        'Moho negro (fumagina) sobre melaza',
        'Crecimiento debilitado',
        'Posible transmisión de virus',
      ],
      treatment: 'Aspira adultos cuidadosamente con aspiradora de mano. Usa trampas amarillas adhesivas. Aplica jabón insecticida o aceite de neem en envés de hojas cada 5-7 días. Lava plantas con agua. Para infestaciones severas, usa insecticida específico (imidacloprid). Introduce parasitoides Encarsia formosa.',
      prevention: 'Inspecciona plantas nuevas cuidadosamente. Usa mallas en ventanas de invernaderos. Planta flores que atraen enemigos naturales. Mantén plantas saludables. Usa mantillo reflectante plateado. Introduce control biológico preventivamente. Remueve hojas muy infestadas. Evita sobre-fertilización nitrogenada.',
      imageUrl: 'https://images.unsplash.com/photo-1516470930681-2d6d21d4e22b?w=800',
    },
    {
      id: 'downy-mildew',
      name: 'Mildiu Velloso',
      type: 'fungal',
      description: 'El mildiu velloso es causado por oomicetes (parientes de algas, no hongos verdaderos) que requieren agua libre para infectar. A diferencia del oídio, prospera en condiciones frescas y húmedas. Produce esporangios que se dispersan por viento y lluvia. Puede destruir cultivos rápidamente.',
      symptoms: [
        'Manchas amarillas angulares en haz de hojas (limitadas por venas)',
        'Crecimiento velloso gris-púrpura en envés de hojas',
        'Manchas que se vuelven marrones y necróticas',
        'Defoliación rápida',
        'Frutos infectados se pudren',
        'Más severo en clima fresco y húmedo',
        'Plantas que colapsan rápidamente',
      ],
      treatment: 'Remueve inmediatamente todas las hojas afectadas. Mejora circulación de aire. Reduce humedad. Aplica fungicida a base de cobre o productos específicos para mildiu velloso (fosetil-aluminio). Evita riego por aspersión. Trata preventivamente si hay condiciones favorables. Ventila invernaderos.',
      prevention: 'Planta variedades resistentes siempre que sea posible. Espaciado amplio para circulación. Riega solo en la base temprano en el día. Evita follaje húmedo durante la noche. Mejora drenaje. Rota cultivos. Remueve plantas voluntarias y malezas. Monitorea pronósticos y trata preventivamente. Ventila invernaderos bien.',
      imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800',
    },
    {
      id: 'verticillium-wilt',
      name: 'Marchitez por Verticillium',
      type: 'fungal',
      description: 'Verticillium dahliae y V. albo-atrum son hongos del suelo que invaden el sistema vascular de plantas. Pueden sobrevivir en el suelo por 10-15 años como estructuras de resistencia. Afectan a más de 300 especies. Más activo en temperaturas frescas a moderadas (21-27°C).',
      symptoms: [
        'Marchitez de ramas individuales o secciones de planta',
        'Amarillamiento que comienza en bordes de hojas',
        'Marchitez en forma de "V" desde bordes hacia centro',
        'Decoloración marrón del tejido vascular (cortar tallo)',
        'Síntomas generalmente en un lado de la planta primero',
        'Defoliación',
        'Muerte eventual de la planta',
        'Síntomas peores en clima cálido',
      ],
      treatment: 'No hay cura. Proporciona cuidado óptimo para prolongar vida de planta. Riega y fertiliza adecuadamente. Poda ramas muertas. Eventualmente remueve planta. No plantes cultivos susceptibles en ese suelo. Solarización del suelo puede reducir inóculo. Considera usar cultivares resistentes en futuro.',
      prevention: 'Planta solo variedades resistentes certificadas cuando estén disponibles. Practica rotación de cultivos larga. Evita plantar susceptibles donde hubo enfermedad. Usa sustrato sin suelo para contenedores. Mantén plantas saludables y sin estrés. Controla nematodos. Desinfecta herramientas. Solariza suelo antes de plantar.',
      imageUrl: 'https://images.unsplash.com/photo-1574263907743-9e0df0c15ba3?w=800',
    },
    {
      id: 'nitrogen-deficiency',
      name: 'Deficiencia de Nitrógeno',
      type: 'deficiency',
      description: 'El nitrógeno es un nutriente móvil esencial para el crecimiento vegetativo y producción de clorofila. La deficiencia es común en sustratos pobres, lixiviación excesiva por sobre-riego, o en plantas de crecimiento rápido. Los síntomas aparecen primero en hojas viejas porque la planta reubica nitrógeno a hojas nuevas.',
      symptoms: [
        'Amarillamiento general de hojas viejas (empezando desde abajo)',
        'Crecimiento lento y atrofiado',
        'Hojas que eventualmente se vuelven completamente amarillas',
        'Tallos delgados y débiles',
        'Hojas pequeñas',
        'Floración y fructificación reducidas',
        'Plantas con aspecto pálido general',
      ],
      treatment: 'Aplica fertilizante rico en nitrógeno inmediatamente. Para resultados rápidos, usa fertilizante líquido (como emulsión de pescado, té de compost). Para liberación sostenida, incorpora compost, estiércol compostado o fertilizante granular. Aplica nitrógeno foliar para corrección rápida. Mejora materia orgánica del suelo.',
      prevention: 'Fertiliza regularmente con fertilizante balanceado durante temporada de crecimiento. Incorpora compost anualmente al suelo. Usa mantillo orgánico que se descompone liberando nitrógeno. Evita sobre-riego que lixivia nutrientes. Analiza suelo periódicamente. Siembra cultivos de cobertura (leguminosas) que fijan nitrógeno. Ajusta pH del suelo (6.0-7.0) para óptima absorción.',
      imageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800',
    },
    {
      id: 'iron-deficiency',
      name: 'Clorosis Férrica',
      type: 'deficiency',
      description: 'El hierro es crucial para la producción de clorofila. Aunque el hierro puede estar presente en el suelo, a menudo no está disponible para las plantas, especialmente en suelos alcalinos (pH > 7.0). La deficiencia de hierro causa clorosis intervenal característica en hojas nuevas porque el hierro es un nutriente inmóvil.',
      symptoms: [
        'Amarillamiento entre venas de hojas nuevas',
        'Venas permanecen verdes (clorosis intervenal)',
        'Hojas nuevas afectadas primero (parte superior de planta)',
        'Hojas pueden volverse casi blancas en casos severos',
        'Crecimiento atrofiado',
        'Muerte de brotes en casos extremos',
        'Hojas más viejas permanecen verdes inicialmente',
      ],
      treatment: 'Aplica quelato de hierro (Fe-EDDHA para pH alto, Fe-EDTA para pH bajo) al suelo según instrucciones. Para corrección rápida, aplica hierro foliar. Ajusta pH del suelo a 6.0-6.5 si está muy alcalino (usa azufre elemental o sulfato de amonio). Mejora drenaje si suelo está encharcado. Incorpora compost para mejorar disponibilidad.',
      prevention: 'Mantén pH del suelo en rango óptimo (6.0-6.5) mediante análisis y ajustes. Evita sobre-riego que puede inducir deficiencia. No sobre-encales suelos. Incorpora materia orgánica que mejora disponibilidad de hierro. Aplica quelato de hierro preventivamente en suelos alcalinos. Para plantas acidófilas (azaleas, arándanos), usa sustratos ácidos específicos.',
      imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    },
    {
      id: 'aloe-rust',
      name: 'Roya del Aloe',
      type: 'fungal',
      description: 'La roya del aloe es causada por Phakopsora pachyrhizi, un hongo específico que afecta principalmente especies de Aloe. Produce manchas de esporas negro-rojizas características. Se propaga por esporas transportadas por viento y se favorece por humedad alta.',
      symptoms: [
        'Manchas negras o marrón-rojizas en hojas',
        'Las manchas contienen pústulas de esporas',
        'Hojas que se marchitan o doblan',
        'Manchas que se expanden formando áreas necróticas',
        'Hojas afectadas eventualmente mueren',
        'Desfiguración de la planta',
      ],
      treatment: 'Remueve y destruye hojas muy afectadas. Aísla plantas infectadas. Mejora circulación de aire alrededor de plantas. Reduce humedad. Aplica fungicida a base de azufre o cobre. Trata cada 10-14 días hasta que los síntomas se controlen. Evita mojar follaje al regar.',
      prevention: 'Proporciona excelente circulación de aire. Espaciado amplio entre plantas. Riega solo en la base. Permite que las hojas se sequen rápidamente. Evita humedad excesiva. Inspecciona regularmente plantas. Mantén plantas saludables con nutrición adecuada pero sin exceso de fertilización.',
      imageUrl: 'https://images.unsplash.com/photo-1596548438137-d51ea5c83ca5?w=800',
    },
    {
      id: 'rose-rust',
      name: 'Roya de las Rosas',
      type: 'fungal',
      description: 'Phragmidium mucronatum es el hongo específico que causa roya en rosas. Produce esporas de diferentes tipos durante el año. Inverna en cañas infectadas. Requiere humedad para infección. Puede causar defoliación severa debilitando plantas.',
      symptoms: [
        'Pústulas naranja brillante en envés de hojas',
        'Manchas amarillas correspondientes en haz de hojas',
        'Las pústulas liberan polvo naranja (esporas)',
        'Defoliación prematura',
        'Lesiones naranja o negras en cañas',
        'Crecimiento debilitado',
        'Reducción en floración',
      ],
      treatment: 'Remueve todas las hojas infectadas inmediatamente. Rastrilla y destruye hojas caídas. Aplica fungicida específico para roya o de amplio espectro cada 7-14 días. Mejora circulación de aire podando si necesario. Evita riego por aspersión. Poda cañas infectadas en invierno.',
      prevention: 'Planta variedades resistentes. Espaciado amplio. Riega solo en la base temprano en el día. Poda sanitaria removiendo cañas infectadas en invierno. Destruye todas las hojas caídas en otoño. Aplica mantillo nuevo en primavera. Fungicidas preventivos en primavera si hubo problemas previos. Mejora circulación de aire.',
      imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
    },
    {
      id: 'thrips',
      name: 'Trips',
      type: 'pest',
      description: 'Los trips son insectos muy pequeños (1-2mm) alargados que se alimentan raspando células de superficie de hojas, flores y frutos. Son difíciles de ver a simple vista. Son especialmente dañinos porque transmiten virus como el virus del bronceado del tomate (TSWV). Prosperan en clima cálido y seco.',
      symptoms: [
        'Rayas plateadas o bronceadas en hojas',
        'Puntos negros pequeños (excremento) en hojas',
        'Hojas deformadas, enrolladas o con cicatrices',
        'Flores deformadas o con manchas',
        'Frutos con cicatrices plateadas o marrones',
        'Insectos alargados muy pequeños visibles con lupa',
        'Transmisión de virus en casos severos',
      ],
      treatment: 'Rocía con agua fuerte para desalojar trips. Aplica jabón insecticida cada 3-5 días. Usa aceite de neem o spinosad. Para infestaciones severas, considera insecticida sistémico. Coloca trampas adhesivas azules. Introduce ácaros depredadores o insectos beneficiosos como Orius. Remueve flores y brotes muy infestados.',
      prevention: 'Usa mallas finas en invernaderos (menos de 0.25mm). Coloca trampas adhesivas azules para monitoreo. Mantén plantas saludables. Elimina malezas que hospedan trips. Introduce control biológico preventivamente. Inspecciona plantas nuevas cuidadosamente. Mantén humedad adecuada. Evita estrés hídrico.',
      imageUrl: 'https://images.unsplash.com/photo-1558377359-ff86d870efc8?w=800',
    },
    {
      id: 'early-blight',
      name: 'Tizón Temprano',
      type: 'fungal',
      description: 'Alternaria solani causa el tizón temprano, común en tomates y papas. A diferencia del tizón tardío, comienza en hojas viejas inferiores y progresa hacia arriba. Las esporas se propagan por viento, lluvia e insectos. Más común en clima cálido y húmedo con rocío nocturno.',
      symptoms: [
        'Manchas marrones circulares en hojas viejas primero',
        'Anillos concéntricos tipo "diana" en manchas (característico)',
        'Halos amarillos alrededor de manchas',
        'Lesiones en tallos con anillos concéntricos',
        'Manchas hundidas en frutos cerca del cáliz',
        'Defoliación progresiva desde abajo hacia arriba',
        'Reducción significativa en rendimiento',
      ],
      treatment: 'Remueve hojas afectadas inferiores. Mejora circulación de aire. Aplica fungicida a base de cobre, mancozeb o clorotalonil cada 7-10 días. Evita mojar follaje. Aumenta espaciamiento. Aplica mantillo para prevenir salpicaduras. Fertiliza adecuadamente para vigor de planta.',
      prevention: 'Usa variedades resistentes cuando posible. Rotación de cultivos 3+ años sin solanáceas. Espaciado amplio y tutores. Riega solo en base temprano en día. Mantillo para evitar salpicaduras. Remueve hojas viejas inferiores. Fertiliza balanceado (evita exceso nitrógeno). Destruye restos de cultivos. Fungicidas preventivos.',
      imageUrl: 'https://images.unsplash.com/photo-1592419044706-39796d40f98c?w=800',
    },
    {
      id: 'anthracnose',
      name: 'Antracnosis',
      type: 'fungal',
      description: 'La antracnosis es causada por varios hongos del género Colletotrichum. Afecta hojas, tallos, flores y frutos de muchas plantas. Produce lesiones hundidas características. Las esporas se propagan por salpicaduras de lluvia. Más severa en clima cálido y húmedo.',
      symptoms: [
        'Manchas hundidas marrones o negras en frutos',
        'Lesiones con anillos concéntricos en frutos maduros',
        'Manchas marrones irregulares en hojas',
        'Lesiones necróticas en tallos',
        'Muerte regresiva de ramas',
        'Masa rosada de esporas en lesiones (clima húmedo)',
        'Caída prematura de hojas y frutos',
      ],
      treatment: 'Remueve y destruye partes afectadas. Mejora circulación de aire podando. Aplica fungicida a base de cobre o productos específicos para antracnosis. Trata preventivamente durante períodos húmedos. Cosecha frutos antes de maduración completa si es viable. Evita salpicaduras al regar.',
      prevention: 'Planta variedades resistentes certificadas. Rotación de cultivos. Espaciado amplio para buena circulación. Tutoreo para evitar contacto con suelo. Riega solo en base sin mojar follaje. Mantillo para evitar salpicaduras. Poda sanitaria. Destruye restos de cultivos. Fungicidas preventivos en climas propensos.',
      imageUrl: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=800',
    },
    {
      id: 'damping-off',
      name: 'Caída de Plántulas',
      type: 'fungal',
      description: 'Complejo de hongos del suelo (Pythium, Rhizoctonia, Fusarium) que atacan semillas y plántulas. Puede ocurrir antes (pre-emergencia) o después de emergencia. Extremadamente común en germinación. Favorecido por sustrato frío, húmedo, compactado y siembra densa.',
      symptoms: [
        'Semillas que no germinan (pudrición pre-emergencia)',
        'Plántulas que colapsan repentinamente',
        'Adelgazamiento del tallo a nivel del suelo (cuello)',
        'Tallo marrón y acuoso en la base',
        'Raíces oscuras y podridas',
        'Plántulas que caen como cortadas',
        'Parches de plántulas muertas',
      ],
      treatment: 'No hay tratamiento efectivo una vez infectada. Remueve plántulas afectadas inmediatamente. Mejora drenaje. Reduce riego. Aumenta temperatura y luz. Ventila bien. Para futuras siembras, usa sustrato esterilizado y trata semillas con fungicida.',
      prevention: 'Usa sustrato esterilizado para germinación. No sobre-riegues; mantén sustrato húmedo pero no empapado. Proporciona temperatura adecuada (21-24°C). Buena circulación de aire. No siembres densamente. Usa contenedores limpios desinfectados. Trata semillas con fungicida. Evita fertilización excesiva. Siembra en sustrato tibio.',
      imageUrl: 'https://images.unsplash.com/photo-1530836176872-14c89f41db1a?w=800',
    },
    {
      id: 'septoria',
      name: 'Septoria o Mancha Foliar del Tomate',
      type: 'fungal',
      description: 'Septoria lycopersici es específico de tomates. Similar al tizón temprano pero con manchas más pequeñas y numerosas con puntos negros (picnidios) en el centro. Comienza en hojas inferiores. Esporas se propagan por lluvia y herramientas. Puede causar defoliación severa.',
      symptoms: [
        'Numerosas manchas pequeñas circulares (3-6mm) en hojas',
        'Manchas con centros grises y bordes oscuros',
        'Puntos negros pequeños en centro de manchas (picnidios)',
        'Comienza en hojas inferiores más viejas',
        'Halos amarillos alrededor de manchas',
        'Defoliación progresiva ascendente',
        'Normalmente no afecta frutos',
      ],
      treatment: 'Remueve hojas afectadas inferiores inmediatamente. Aplica fungicida a base de cobre, mancozeb o clorotalonil cada 7-10 días. Mejora circulación de aire. Evita mojar follaje. Aplica mantillo grueso. Continúa tratamiento toda la temporada. Desinfecta herramientas entre plantas.',
      prevention: 'Usa trasplantes certificados libres de enfermedad. Rotación de 3+ años. Espaciado amplio (90cm+). Tutoreo vertical. Riega solo en base temprano. Mantillo espeso. Remueve hojas inferiores proactivamente. No trabajes con plantas mojadas. Destruye restos de plantas. Fungicidas preventivos protectores.',
      imageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800',
    },
    {
      id: 'fusarium-wilt',
      name: 'Marchitez por Fusarium',
      type: 'fungal',
      description: 'Fusarium oxysporum existe en muchas formas especializadas que atacan plantas específicas. Invade sistema vascular bloqueando transporte de agua. Puede sobrevivir en suelo muchos años. Más activo en temperaturas cálidas (27-32°C) a diferencia de Verticillium.',
      symptoms: [
        'Marchitez de hojas inferiores primero',
        'Amarillamiento de un solo lado de hoja o planta',
        'Marchitez durante día que mejora de noche (al inicio)',
        'Decoloración marrón del sistema vascular (cortar tallo)',
        'Crecimiento atrofiado',
        'Muerte eventual de planta completa',
        'Síntomas peores en clima cálido',
      ],
      treatment: 'No hay cura. Remueve plantas infectadas inmediatamente con raíces. No compostes. Desinfecta herramientas con lejía 10%. Mejora drenaje. Solariza suelo en verano. No plantes cultivos susceptibles por 5+ años. Considera cultivar en contenedores con sustrato fresco o usar variedades resistentes.',
      prevention: 'Planta únicamente variedades resistentes (buscamarque F, FF o FFF en tomates). Rotación larga. Usa sustrato sin suelo para contenedores. Mantén pH ligeramente ácido (6.5). Evita heridas en raíces. Control de nematodos. Practica higiene estricta. Solarización del suelo. Mantén plantas sin estrés.',
      imageUrl: 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=800',
    },
    {
      id: 'potassium-deficiency',
      name: 'Deficiencia de Potasio',
      type: 'deficiency',
      description: 'El potasio es móvil y esencial para regulación de agua, fotosíntesis, producción de azúcares y calidad de frutos. Deficiencia común en suelos arenosos, lixiviación excesiva, o cuando hay exceso de calcio/magnesio que bloquea absorción. Síntomas aparecen primero en hojas viejas.',
      symptoms: [
        'Bordes y puntas de hojas viejas amarillentas o marrones (necrosis marginal)',
        'Quemado progresivo de bordes hacia dentro',
        'Manchas necróticas entre venas',
        'Hojas que se curvan hacia abajo',
        'Tallos débiles que se doblan',
        'Frutos pequeños de mala calidad',
        'Floración reducida',
        'Mayor susceptibilidad a enfermedades',
      ],
      treatment: 'Aplica fertilizante rico en potasio (alto número K en NPK, ej: 5-10-15). Para corrección rápida, usa sulfato de potasio o nitrato de potasio disuelto. Aplica fertilizante foliar de potasio. Incorpora ceniza de madera (con moderación, eleva pH). Aplica compost maduro rico en potasio.',
      prevention: 'Fertiliza regularmente con fertilizante balanceado o rico en potasio durante fructificación. Analiza suelo periódicamente. Mejora suelos arenosos con compost. Evita sobre-riego que lixivia potasio. Mantén pH 6.0-7.0 para óptima absorción. Evita exceso de calcio o magnesio. Usa fertilizante de liberación lenta.',
      imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    },
    {
      id: 'magnesium-deficiency',
      name: 'Deficiencia de Magnesio',
      type: 'deficiency',
      description: 'El magnesio es el átomo central de la clorofila y móvil en la planta. Deficiencia común en suelos ácidos, arenosos, o cuando hay exceso de potasio/calcio. Más frecuente durante períodos de crecimiento rápido o fructificación. Síntomas característicos en hojas viejas primero.',
      symptoms: [
        'Clorosis intervenal en hojas viejas (venas verdes, entre venas amarillo)',
        'Patrón de "árbol de Navidad" en hojas (V invertida verde)',
        'Progresa desde hojas inferiores hacia arriba',
        'Bordes de hojas pueden volverse rojizos o púrpura',
        'Hojas eventualmente necróticas y caen',
        'Floración y fructificación reducidas',
        'Frutos de menor calidad',
      ],
      treatment: 'Aplica sulfato de magnesio (sal de Epsom): 1 cucharada por 4 litros de agua cada 2 semanas. Para corrección rápida, aplica spray foliar de sulfato de magnesio (1 cucharada por litro). Incorpora dolomita al suelo si pH es bajo. Usa fertilizante que contenga magnesio.',
      prevention: 'Analiza suelo regularmente. Mantén pH entre 6.0-7.0. Aplica dolomita (fuente de calcio y magnesio) si pH es bajo. Usa fertilizante completo que incluya magnesio. Evita exceso de potasio que bloquea magnesio. Incorpora compost que contiene magnesio. En hidroponia, asegura que solución nutritiva contenga magnesio.',
      imageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800',
    },
    {
      id: 'calcium-deficiency',
      name: 'Deficiencia de Calcio',
      type: 'deficiency',
      description: 'El calcio es inmóvil en plantas, necesario para estructura celular y crecimiento. Deficiencia causa problemas en tejidos jóvenes y frutos en desarrollo. "Pudrición apical" en tomates/pimientos es deficiencia de calcio, aunque puede haber calcio suficiente pero riego irregular impide transporte.',
      symptoms: [
        'Pudrición apical en tomates/pimientos (mancha negra hundida en base de fruto)',
        'Puntas de hojas jóvenes quemadas o muertas',
        'Hojas nuevas deformadas o enrolladas',
        'Necrosis de puntos de crecimiento',
        'Frutos con manchas corchosas internas',
        'Hojas nuevas pálidas',
        'Raíces cortas y gruesas',
      ],
      treatment: 'Para pudrición apical: mejora riego (consistente, no errático). Aplica nitrato de calcio disuelto (1 cucharada por 4 litros). Spray foliar de cloruro de calcio en frutos. Mantén humedad uniforme del suelo con mantillo. Revisa pH (debe estar 6.0-7.0). Evita exceso de nitrógeno amónico que interfiere.',
      prevention: 'Mantén riego consistente y regular (crítico). Aplica mantillo para humedad uniforme. Analiza y ajusta pH del suelo (6.0-7.0). Incorpora cal dolomítica si calcio es bajo. Evita exceso de potasio/magnesio que bloquean calcio. No sobre-fertilices con nitrógeno. Evita daños a raíces. En contenedores, usa fertilizante completo con calcio.',
      imageUrl: 'https://images.unsplash.com/photo-1583051331670-2fdf4ab50c1f?w=800',
    },
    {
      id: 'leafminers',
      name: 'Minadores de Hojas',
      type: 'pest',
      description: 'Los minadores son larvas de pequeñas moscas, polillas o avispas que se alimentan entre las capas de tejido foliar creando túneles o "minas" serpenteantes características. Aunque estéticamente desagradables, rara vez matan plantas pero debilitan vigor y pueden transmitir enfermedades.',
      symptoms: [
        'Líneas serpenteantes blancas, amarillas o marrones en hojas',
        'Túneles o manchas tipo "ampolla" en hojas',
        'Larvas pequeñas visibles dentro de minas',
        'Puntos negros (excremento) dentro de túneles',
        'Hojas severamente minadas caen prematuramente',
        'Pequeñas moscas negras y amarillas alrededor de plantas',
      ],
      treatment: 'Remueve y destruye hojas muy afectadas. Aplasta larvas dentro de minas con dedos. Usa trampas amarillas adhesivas para adultos. Aplica aceite de neem que mata larvas dentro de hojas. Para infestaciones severas, usa insecticida sistémico (imidacloprid, spinosad). Introduce parasitoides como Diglyphus isaea.',
      prevention: 'Usa cubiertas flotantes en cultivos susceptibles. Coloca trampas amarillas para monitoreo y captura. Remueve malezas que hospedan minadores. Mantén plantas vigorosas. Introduce control biológico preventivamente. Inspecciona plantas nuevas. Rota cultivos para interrumpir ciclo. Cultiva variedades menos atractivas.',
      imageUrl: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=800',
    },
    {
      id: 'caterpillars',
      name: 'Orugas y Gusanos',
      type: 'pest',
      description: 'Las orugas son larvas de mariposas y polillas que mastican follaje, flores, frutos y tallos. Incluyen gusanos del tomate (hornworms), gusanos cortadores, gusanos del repollo, y loopers. Pueden causar defoliación rápida y severa. Algunas orugas barrenan frutos o tallos.',
      symptoms: [
        'Agujeros grandes irregulares masticados en hojas',
        'Hojas completamente devoradas, solo quedan venas',
        'Excremento oscuro tipo pellet en hojas',
        'Orugas visibles en plantas (verdes, marrones, rayadas)',
        'Frutos con agujeros de entrada',
        'Tallos cortados a nivel del suelo (gusanos cortadores)',
        'Telarañas en algunos casos',
      ],
      treatment: 'Recoge orugas manualmente (usa guantes, algunas tienen pelos irritantes). Aplica Bacillus thuringiensis (Bt) que mata específicamente orugas. Usa spinosad para control orgánico. Para infestaciones severas, aplica insecticida piretrina. Busca y destruye masas de huevos. Aplica barreras en tallos contra gusanos cortadores.',
      prevention: 'Inspecciona regularmente envés de hojas buscando huevos y orugas pequeñas. Usa cubiertas flotantes durante vuelo de adultos. Coloca collares en plántulas contra gusanos cortadores. Cultiva plantas que atraen avispas parasitoides y pájaros. Mantén jardín limpio sin malezas. Ara suelo en otoño para exponer pupas. Usa luces o trampas de feromonas para adultos.',
      imageUrl: 'https://images.unsplash.com/photo-1558377359-ff86d870efc8?w=800',
    },
    {
      id: 'slugs-snails',
      name: 'Babosas y Caracoles',
      type: 'pest',
      description: 'Moluscos terrestres que se alimentan masticando tejido vegetal tierno. Activos de noche y en días nublados/húmedos. Dejan rastros plateados de baba característicos. Prosperan en ambientes húmedos con abundante refugio. Pueden causar daño severo especialmente a plántulas.',
      symptoms: [
        'Agujeros grandes irregulares en hojas',
        'Bordes de hojas comidos',
        'Plántulas completamente devoradas',
        'Rastros plateados brillantes de baba en hojas y suelo',
        'Daño principalmente nocturno',
        'Babosas/caracoles visibles de noche o días húmedos',
        'Frutos comidos cerca del suelo',
      ],
      treatment: 'Recoge manualmente de noche o temprano en mañana. Coloca trampas de cerveza (platos hundidos con cerveza). Usa cebo para babosas (fosfato férrico es seguro). Crea barreras de cobre alrededor de plantas. Espolvorea tierra de diatomeas alrededor de plantas. Elimina refugios (piedras, maleza, tablas). Atrae pájaros, erizos, sapos.',
      prevention: 'Riega temprano en día para que superficie seque de noche. Elimina refugios diurnos (maleza, escombros, tablas). Mantén área limpia sin restos vegetales. Usa mantillo grueso de materiales ásperos. Crea barreras de cobre, cascara de huevo triturada, o grava. Cultiva en camas elevadas. Reduce riego excesivo.',
      imageUrl: 'https://images.unsplash.com/photo-1530836176872-14c89f41db1a?w=800',
    },
    {
      id: 'nematodes',
      name: 'Nematodos Fitoparásitos',
      type: 'pest',
      description: 'Gusanos microscópicos del suelo que parasitan raíces. Los nematodos agalladores (Meloidogyne) forman agallas características. Nematodos lesionadores causan lesiones necróticas. Debilitan plantas, reducen absorción de nutrientes y agua, y crean heridas que permiten entrada de patógenos.',
      symptoms: [
        'Crecimiento lento y atrofiado sin causa aparente',
        'Marchitez durante día a pesar de riego adecuado',
        'Amarillamiento y hojas pequeñas',
        'Raíces con agallas o nódulos hinchados (nematodos agalladores)',
        'Raíces oscuras con lesiones (nematodos lesionadores)',
        'Sistema radicular reducido y poco ramificado',
        'Mayor susceptibilidad a marchiteces y pudriciones',
      ],
      treatment: 'No hay tratamiento químico disponible para jardineros domésticos. Remueve plantas severamente infectadas. Solariza suelo (cubrir con plástico transparente 6-8 semanas en verano). Incorpora compost/materia orgánica que promueve enemigos naturales. Usa nematodos beneficiosos depredadores. Cultiva en contenedores con sustrato fresco.',
      prevention: 'Planta variedades resistentes (buscas marca N en tomates). Rotación larga con cultivos no susceptibles. Intercala caléndulas que suprimen nematodos. Solariza suelo antes de plantar. Incorpora compost maduro. Mantén pH ligeramente ácido. Planta cultivos de cobertura (mostaza, sudangrass). Usa sustrato sin suelo en contenedores. Evita trasladar suelo infestado.',
      imageUrl: 'https://images.unsplash.com/photo-1574263907743-9e0df0c15ba3?w=800',
    },
    {
      id: 'sooty-mold',
      name: 'Fumagina o Moho de Hollín',
      type: 'fungal',
      description: 'La fumagina no es parásita de plantas sino saprófita que crece sobre melaza secretada por insectos chupadores (pulgones, cochinillas, moscas blancas). Forma capa negra hollín-como que bloquea luz y reduce fotosíntesis. Es cosmética pero indica infestación de plagas.',
      symptoms: [
        'Capa negra en polvo tipo hollín en hojas y tallos',
        'Sustancia negra que se frota fácilmente',
        'Coating negro en hojas superiores e inferiores',
        'Presencia de melaza pegajosa debajo del moho',
        'Pulgones, cochinillas u otras plagas presentes',
        'Hojas que amarillean por falta de luz',
        'Principalmente problema estético',
      ],
      treatment: 'Lava hojas con agua jabonosa para remover moho. Trata la plaga subyacente (pulgones, cochinillas, moscas blancas) con métodos apropiados. Mejora circulación de aire. Aplica aceite de neem que controla plagas y ayuda a limpiar moho. Una vez controlada la plaga, la fumagina no regresará.',
      prevention: 'Controla insectos chupadores que producen melaza. Inspecciona plantas regularmente. Mantén plantas saludables. Fomenta insectos beneficiosos. Lava plantas con agua ocasionalmente. Buena circulación de aire. Aislamiento de plantas infestadas. Control preventivo de plagas.',
      imageUrl: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=800',
    },
    {
      id: 'canker',
      name: 'Cancro',
      type: 'bacterial',
      description: 'Los cancros son lesiones hundidas en corteza causadas por hongos o bacterias. Interfieren con transporte de agua y nutrientes en ramas. Pueden circungirar ramas causando muerte. Común en árboles frutales y ornamentales. Patógenos entran por heridas. Favorecido por estrés.',
      symptoms: [
        'Lesiones hundidas en corteza de ramas o tronco',
        'Área muerta con corteza agrietada',
        'Exudación de goma o resina (gomosis)',
        'Marchitez y muerte de ramas más allá del cancro',
        'Hojas que amarillean en ramas afectadas',
        'Cancros pueden circungirar ramas causando muerte',
        'Corteza descolorida alrededor de lesiones',
      ],
      treatment: 'Poda ramas afectadas 15-30cm debajo del cancro en clima seco. Desinfecta herramientas con alcohol entre cortes. Mejora salud general del árbol con riego y fertilización adecuados. Evita heridas. Aplica fungicida o bactericida a base de cobre en heridas. En casos severos en tronco, consulta arborista.',
      prevention: 'Mantén árboles saludables sin estrés (riego, nutrición adecuados). Evita heridas en corteza (cuidado con herramientas). Poda correctamente en época apropiada. Desinfecta herramientas. Protege árboles de daño invernal. Blanquea troncos para prevenir rajaduras por sol. Planta variedades resistentes. Evita sobre-fertilización que causa crecimiento suculento.',
      imageUrl: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=800',
    },
    {
      id: 'fire-blight',
      name: 'Fuego Bacteriano',
      type: 'bacterial',
      description: 'Erwinia amylovora causa esta devastadora enfermedad bacterial en rosáceas (manzanos, perales, membrillos). Llamada "fuego" porque tejidos infectados parecen quemados. Se propaga por insectos, lluvia, herramientas. Puede matar árboles rápidamente. Más activa en primavera cálida y húmeda.',
      symptoms: [
        'Ramas que se ven quemadas, negras o cafés',
        'Flores marchitas que permanecen en árbol',
        'Exudación bacterial lechosa o ámbar en ramas',
        'Brotes que se curvan en forma de cayado de pastor',
        'Cancros hundidos en ramas con márgenes agrietados',
        'Hojas negras que permanecen adheridas',
        'Muerte rápida de ramas y potencialmente árbol completo',
      ],
      treatment: 'Poda ramas infectadas 30-60cm debajo de síntomas visibles en clima seco. Desinfecta herramientas con lejía 10% entre cada corte. Quema o descarta ramas infectadas. Aplica bactericida a base de cobre o estreptomicina durante floración. Remueve flores infectadas inmediatamente. En casos severos, puede requerir remoción total del árbol.',
      prevention: 'Planta variedades resistentes certificadas. Evita fertilización excesiva con nitrógeno que produce crecimiento suculento. Poda solo en dormancia y desinfecta herramientas. Remueve flores infectadas inmediatamente. Aplica bactericida preventivo durante floración en áreas propensas. Controla insectos vectores. Evita riego por aspersión. Inspecciona regularmente durante primavera.',
      imageUrl: 'https://images.unsplash.com/photo-1592419044706-39796d40f98c?w=800',
    },
    {
      id: 'leaf-curl',
      name: 'Rizado de Hojas',
      type: 'fungal',
      description: 'Taphrina deformans causa el rizado del durazno, la enfermedad más común en durazneros y nectarinos. Esporas invernan en corteza y yemas, infectando hojas nuevas en primavera durante clima fresco y húmedo. Puede causar defoliación severa debilitando árboles.',
      symptoms: [
        'Hojas nuevas engrosadas, distorsionadas y enrolladas',
        'Hojas con coloración rojiza, púrpura o amarillenta',
        'Hojas con aspecto ampollado o arrugado',
        'Capa blanca en polvo en hojas afectadas',
        'Caída prematura de hojas',
        'Frutos deformados y con lesiones',
        'Brotes débiles y acortados',
        'Debilitamiento del árbol',
      ],
      treatment: 'Remueve hojas infectadas apenas aparezcan. Aplica fungicida a base de cobre una vez que hojas hayan caído en otoño y nuevamente antes de yema hinchada en primavera. No hay tratamiento efectivo una vez hojas están infectadas. Fertiliza y riega para mantener vigor del árbol.',
      prevention: 'Aplica fungicida a base de cobre o cal sulfurada en otoño después de caída de hojas y en invierno/primavera temprana antes de yema hinchada. Dos aplicaciones críticas: una en otoño y otra en invierno tardío. Planta variedades resistentes. Poda para buena circulación de aire. Rastrilla y destruye hojas caídas. Mantén árbol saludable.',
      imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
    },
    {
      id: 'bacterial-speck',
      name: 'Moteado Bacteriano',
      type: 'bacterial',
      description: 'Pseudomonas syringae pv. tomato causa moteado bacteriano en tomates. Similar a mancha bacteriana pero lesiones son más pequeñas. Prospera en clima fresco y húmedo (15-24°C). Se propaga por lluvia, herramientas, semillas infectadas. Puede causar pérdidas significativas.',
      symptoms: [
        'Pequeñas manchas negras en hojas (1-2mm)',
        'Manchas con halos amarillos prominentes',
        'Lesiones necróticas en tallos y peciolos',
        'Pequeñas manchas levantadas en frutos verdes',
        'Manchas en frutos con centro oscuro',
        'Defoliación en infecciones severas',
        'Más común en clima fresco',
      ],
      treatment: 'Remueve plantas muy infectadas. Aplica bactericida a base de cobre cada 7-10 días. Mejora circulación de aire. Evita mojar follaje. Reduce humedad. Trata preventivamente durante períodos favorables. Desinfecta herramientas. No trabajes con plantas mojadas.',
      prevention: 'Usa semillas y trasplantes certificados libres de enfermedad. Planta variedades resistentes. Rotación de 3+ años. Espaciado amplio. Tutoreo. Riega solo en base temprano. Mantillo para evitar salpicaduras. Evita trabajar con plantas mojadas. Desinfecta herramientas. Bactericida de cobre preventivo. Destruye restos de cultivos.',
      imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=800',
    },
    {
      id: 'cercospora',
      name: 'Mancha Foliar por Cercospora',
      type: 'fungal',
      description: 'Cercospora es un género amplio de hongos que causa manchas foliares en muchas plantas. Común en remolachas, acelgas, rosales. Produce manchas características con centros grises o bronceados y bordes púrpuras. Esporas se propagan por viento y salpicaduras.',
      symptoms: [
        'Manchas circulares con centros grises o bronceados',
        'Bordes púrpuras o rojizos alrededor de manchas',
        'Manchas pueden tener apariencia de "ojo de rana"',
        'Hojas que amarillean alrededor de manchas',
        'Defoliación prematura en infecciones severas',
        'Manchas pueden fusionarse',
        'Más severo en clima cálido y húmedo',
      ],
      treatment: 'Remueve y destruye hojas muy afectadas. Mejora circulación de aire. Aplica fungicida a base de cobre, mancozeb o azoxistrobina cada 7-14 días. Evita mojar follaje al regar. Reduce humedad foliar. Continúa tratamiento si condiciones favorables persisten.',
      prevention: 'Planta variedades resistentes cuando disponibles. Rotación de cultivos. Espaciado amplio para ventilación. Riega solo en base temprano en día. Remueve hojas viejas inferiores. Mantillo para evitar salpicaduras. Destruye restos de cultivos. Fungicidas preventivos en climas propensos. Evita fertilización excesiva con nitrógeno.',
      imageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800',
    },
    {
      id: 'chlorosis',
      name: 'Clorosis General',
      type: 'deficiency',
      description: 'Clorosis es el amarillamiento  de tejido por falta de clorofila. Puede ser causada por deficiencias de múltiples nutrientes (hierro, nitrógeno, magnesio, azufre, zinc, manganeso), pH inadecuado, encharcamiento, enfermedades radicales, o estrés ambiental. Diagnóstico requiere observar patrón específico.',
      symptoms: [
        'Amarillamiento general o parcial de hojas',
        'Patrón depende de causa específica',
        'Puede afectar hojas viejas o nuevas según nutriente',
        'Venas pueden permanecer verdes o amarillear también',
        'Crecimiento lento',
        'Hojas pequeñas',
        'Reducción en vigor',
      ],
      treatment: 'Identifica la causa específica mediante análisis del patrón de clorosis y análisis de suelo. Trata según deficiencia identificada. Revisa y ajusta pH del suelo. Mejora drenaje si está encharcado. Aplica fertilizante completo balanceado. Trata enfermedades radicales si presentes. Mejora condiciones de crecimiento.',
      prevention: 'Mantén pH del suelo en rango óptimo (6.0-7.0 para mayoría de plantas). Fertiliza regularmente con fertilizante completo balanceado. Asegura buen drenaje. Analiza suelo cada 2-3 años. Incorpora compost anualmente. Riega adecuadamente sin encharcar. Mantén plantas libres de plagas y enfermedades. Usa sustrato de calidad.',
      imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    },
    {
      id: 'edema',
      name: 'Edema o Intumescencia',
      type: 'deficiency',
      description: 'Edema es un desorden fisiológico, no una enfermedad. Ocurre cuando raíces absorben agua más rápido de lo que puede transpirar. Células se hinchan y revientan. Común en geranios, coles, tomates, pimientos. Favorecido por humedad alta, suelo húmedo, luz baja, temperatura fría.',
      symptoms: [
        'Protuberancias o ampollas pequeñas en envés de hojas',
        'Lesiones corchosas o verrugosas en hojas',
        'Lesiones pueden estallar dejando cráteres',
        'Inicialmente verdes, luego marrones o blancas',
        'Principalmente en hojas inferiores',
        'Tallos pueden desarrollar lesiones elevadas',
        'No contagioso',
      ],
      treatment: 'Reduce riego significativamente. Mejora ventilación y circulación de aire. Aumenta luz si posible. Eleva temperatura si está fría. Permite que sustrato seque más entre riegos. Reduce humedad ambiental. Las lesiones existentes no desaparecen pero nuevas hojas crecerán sanas.',
      prevention: 'Riega apropiadamente, evita mantener suelo constantemente húmedo. Mejora circulación de aire. Proporciona luz adecuada. Evita cambios bruscos de temperatura. Reduce humedad ambiental. Usa sustrato bien drenante. No sobre-riegues especialmente en clima frío o nublado. Ventila invernaderos adecuadamente.',
      imageUrl: 'https://images.unsplash.com/photo-1583051331670-2fdf4ab50c1f?w=800',
    },
    {
      id: 'sunscald',
      name: 'Quemadura Solar',
      type: 'deficiency',
      description: 'Quemadura solar es daño fisiológico por exposición excesiva a luz solar intensa, especialmente cuando plantas acostumbradas a sombra se exponen súbitamente al sol, o en frutos expuestos por defoliación. Más común en tomates, pimientos, manzanas. No es contagioso.',
      symptoms: [
        'Manchas blancas, amarillas o bronceadas en lado expuesto al sol',
        'Áreas afectadas se vuelven papiráceas',
        'Parches hundidos en frutos',
        'Tejido afectado eventualmente se pudre',
        'Hojas con áreas blanqueadas o amarillentas',
        'Principalmente en lado sur o expuesto',
        'Más común durante olas de calor',
      ],
      treatment: 'No hay tratamiento para tejido ya dañado. Proporciona sombra temporal (tela de sombra 30-50%) durante calor extremo. Mantén follaje saludable para proteger frutos. Riega adecuadamente durante clima caliente. Frutos afectados levemente aún son comestibles (corta parte dañada).',
      prevention: 'Aclimata plantas gradualmente cuando las muevas de sombra a sol (endurece). Mantén follaje saludable para sombrear frutos. Usa tela de sombra durante clima extremo. En invernaderos, usa sombreado o blanquea techo. Riega y fertiliza apropiadamente para vigor. Planta variedades más tolerantes al calor. Evita poda excesiva que expone frutos.',
      imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    },
  ];

  // Métodos para plantas
  findAllPlants(): PlantDto[] {
    return this.plants;
  }

  findPlantById(id: string): PlantDto {
    const plant = this.plants.find((p) => p.id === id);
    if (!plant) {
      throw new NotFoundException(`Planta con ID ${id} no encontrada`);
    }
    return plant;
  }

  findPlantsByCategory(category: string): PlantDto[] {
    return this.plants.filter((p) => p.category.toLowerCase() === category.toLowerCase());
  }

  createPlant(createPlantDto: CreatePlantDto): PlantDto {
    const newPlant: PlantDto = {
      id: (this.plants.length + 1).toString(),
      ...createPlantDto,
    };
    this.plants.push(newPlant);
    return newPlant;
  }

  updatePlant(id: string, updatePlantDto: UpdatePlantDto): PlantDto {
    const plantIndex = this.plants.findIndex((p) => p.id === id);
    if (plantIndex === -1) {
      throw new NotFoundException(`Planta con ID ${id} no encontrada`);
    }
    this.plants[plantIndex] = {
      ...this.plants[plantIndex],
      ...updatePlantDto,
    };
    return this.plants[plantIndex];
  }

  deletePlant(id: string): void {
    const plantIndex = this.plants.findIndex((p) => p.id === id);
    if (plantIndex === -1) {
      throw new NotFoundException(`Planta con ID ${id} no encontrada`);
    }
    this.plants.splice(plantIndex, 1);
  }

  // Métodos para enfermedades
  findAllDiseases(): DiseaseDto[] {
    return this.diseases;
  }

  findDiseaseById(id: string): DiseaseDto {
    const disease = this.diseases.find((d) => d.id === id);
    if (!disease) {
      throw new NotFoundException(`Enfermedad con ID ${id} no encontrada`);
    }
    return disease;
  }

  findDiseasesByType(type: string): DiseaseDto[] {
    return this.diseases.filter((d) => d.type === type);
  }

  findDiseasesByPlantId(plantId: string): DiseaseDto[] {
    const plant = this.findPlantById(plantId);
    if (!plant.commonDiseases || plant.commonDiseases.length === 0) return [];
    
    return this.diseases.filter((d) => plant.commonDiseases!.includes(d.id));
  }

  createDisease(createDiseaseDto: CreateDiseaseDto): DiseaseDto {
    const newDisease: DiseaseDto = {
      id: `disease-${this.diseases.length + 1}`,
      ...createDiseaseDto,
    };
    this.diseases.push(newDisease);
    return newDisease;
  }
}
